### ISSUE TITLE
i18n filter

### ISSUE THREAD

**Issue by alkos** [lavinjj/angularjs-localizationservice#37]
Hi,
maybe I'm missing something:

    .filter('i18n', ['localize', function (localize) {
        return function (input) {    
               //when I print
               console.log(localize);
               //I can se whole object with filled dictionary and etc...
    
              //but when I use method or property e.g.
              console.log(localize.dictionary)
              //I get empty array
    
              //likewise this returns empty string
               return localize.getLocalizedString(input);            
        };
    }])

Other directives works ok.

**Comment by gbergamo** [comment]
I´m facing the same issue.
I try:
if (localize.dictionary.length === 0) {
    localize.initLocalizedResources();
}

Works, but in browser console I had I lot of errors.

**Comment by lavinjj** [comment]
First can you tell me if you are seeing any data being returned? You can set a breakpoint in the successCallback and see if localize.dictionary is getting anything assigned to it. If the breakpoint is not being hit, then make sure you have a file named resources-locale_en.js or resources-locale_default.js in the i18n folder of your app. You should see network errors with 404 not found errors if the file is missing.

From there we can figure out what the next step is.

**Comment by alkos** [comment]
No data is returned, that's for sure. I put breakpoints, and conclude this: 
i18n filter doesn't wait for successful download of resource files.
Directives "listen" for broadcast 'localizeResourcesUpdated' and in scope.on calls function to translate string..

**Comment by gbergamo** [comment]
In my case dictionary has data. 
I set a breakpoint on filter and successCallback. the filter´s breakpoint was hit before he function´s. I think this happened because async calls.
Using i18nAttr resolve my problem, but I want to use directly {{'_thisway_'|i18n}}

**Comment by lavinjj** [comment]
One way to make sure there is data is to call the initLocalizedResources method in a .run function in your app.js so that the dictionary gets loaded before angular starts to render the page. The filter should still be evaluated in each digest loop, meaning that once the dictionary has data it should get a value.

Also, filter's are not the best when it comes to performance. filters are evaluated in every digest loop, meaning if you have a bunch of filters in your view they are going to be hit continuously. That is why I created the other directives. instead of {{'thisway'|i18n}} try using <div i18n='thisway'></div> and you should get a result and mush better performance since the directive will only be hit when the tag changes value.

**Comment by alkos** [comment]
Yep, I'll try it. The main reason why filter is translation of placeholder content... Thanx! :)

**Comment by lavinjj** [comment]
The i18nAttr directive will work better than the i18n filter. Mainly because it will not be evaluated over and over as you modify the form on the view. Your code will then be i18n-attr='thisway|placeholder' that is exactly why I added the i18nAttr directive.

**Comment by alkos** [comment]
Perfect!  one of those situation where u picture doing something in one way and u r blind for anything else :)) thanx!
